### ISSUE TITLE
Re-open Vial, all layers will shift-up one-line except base layer

### ISSUE THREAD

**Issue by white1033** [jamessa/Pragmatic#9]
On Paramatic 36, if you open VIAL, your layer mapping will shift up one line except the base layer

**Comment by andrewliang25** [comment]
Having same issue on Pragmatic 42: mess up key settings on all layer except layer 0 after modify key on VIAL and refreshing.

**Comment by jamessa** [comment]
Please upgrade to  latest firmware https://github.com/jamessa/Pragmatic/releases/tag/v4.0

Firmware upgrade instruction here https://github.com/jamessa/Pragmatic#更新韌體

**Comment by jamessa** [comment]
root cause, inherited configuration for Pragmatic 56 https://github.com/jamessa/vial-qmk/commit/8f316310044edeee5320d1541d921a957f767331

**Comment by white1033** [comment]
fix the issue after update firmware, thx @jamessa

**Comment by andrewliang25** [comment]
Pragmatic 42 issue fix after firmware update.
